name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install deps
      run: sudo apt-get install verilator cmake
    - name: configure
      run: ./configure
    - name: make
      run: make
    - name: make check
      run: make check
